import Head from "next/head";
import React from "react";
import Navigation from "./Navigation";

const PageLayout = ({ children, title = "News App", header }) => {
  return (
    <>
      <Head>
        <title>{title}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navigation />
      <header style={{ padding: "1rem 2rem" }}>
        <h2>{header}</h2>
      </header>
      <main>{children}</main>
    </>
  );
};

export default PageLayout;
